name: sw1dto2d CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          python -m venv sw1dto2d_env
          source sw1dto2d_env/bin/activate
          python -m pip install --upgrade pip
          pip install -e . && pip install -e .[dev]
        working-directory: .

      - name: Run tests
        run: |
          pytest
        working-directory: .

      - name: Build and upload to PyPI
        run: |
          python -m build
          twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWD }}
        working-directory: .
